# Blackjack Environment Configuration
# Inherits from base.yaml

# Base environment parameters (can override base.yaml)
tokenizer_name: "NousResearch/DeepHermes-3-Llama-3-8B-Preview"
group_size: 32
use_wandb: true
max_num_workers: 32
rollout_server_url: "http://localhost:8000"
total_steps: 1000
batch_size: 1024
steps_per_eval: 20
max_token_length: 15360
wandb_name: "blackjack_tool_calling"
ensure_scores_are_not_same: true

# Blackjack specific configuration
blackjack:
  # Environment parameters
  env_name: "Blackjack-v1"
  temperature: 0.7
  top_p: 0.9
  max_turns: 100
  thinking_active: true
  debug_mode: false
  
  # Reward function configuration
  reward_functions: ["format", "tool_calling"]
  format_reward_weight: 0.5
  environment_reward_weight: 0.5

# Server configuration
server_configs:
  - model_name: "NousResearch/DeepHermes-3-Llama-3-8B-Preview"
    base_url: "http://localhost:9004/v1"
    api_key: "x"
    num_requests_for_eval: 256