# Configuration for 2048 game environment
env:
  group_size: 16
  max_batches_offpolicy: 3
  tokenizer_name: "Qwen/Qwen2.5-1.5B-Instruct"
  use_wandb: true
  rollout_server_url: "http://localhost:8000"
  wandb_name: "atropos_2048"
  ensure_scores_are_not_same: true
  max_token_length: 4096
  data_path_to_save_groups: null
  include_messages: true

# OpenAI server configurations
openai:
  - model_name: "Qwen/Qwen2.5-1.5B-Instruct"
    base_url: "http://localhost:9001/v1"
    api_key: "x"
    weight: 1.0
    num_requests_for_eval: 64

slurm: false
testing: false 